import { Breakpoints } from './breakpoints'

export const TailwindPrefixes = [
  ...Breakpoints,
  'dark',
  'hover',
  'focus',
  'active',
  'after',
  'before',
  'first',
  'last',
  'odd',
  'even',
  'disabled',
  'invalid',
  'read-only',
  'indeterminate',
  'checked',
  'file',
  'marker',
  'placeholder',
  'selection',
  'first-line',
  'first-letter',
  'backdrop',
  'motion-reduce',
  'motion-safe',
  'contrast-more',
  'portrait',
  'landscape',
  'print',
  /supports-\[.+?\]/,
  /group-\w+?-\w+/,
  /peer-\w+?-\w+/,
]
