import { ImageFileType, ImageFormat } from '@prisma/client'
import { categories } from './categories'
import { getRandomProductReviews } from './reviews'
import { gen } from './seed-ids'
import { variants } from './variants'

const imageAt = gen.at('images')
const at = gen.at('products')

export const products = [
  {
    id: at(0),
    name: 'Club Room® Fitted Button Up Shirt',
    images: [
      {
        id: imageAt(0),
        url: 'https://res.cloudinary.com/dgpl87wy6/image/upload/v1688063234/shop/mens-dress-shirt-black_ubopcn.jpg',
        variantId: variants.black.id,
        fileType: ImageFileType.JPG,
        format: ImageFormat.PORTRAIT,
      },
      {
        id: imageAt(1),
        url: 'https://res.cloudinary.com/dgpl87wy6/image/upload/v1688063233/shop/mens-dress-shirt-white_ng0zo1.jpg',
        variantId: variants.white.id,
        fileType: ImageFileType.JPG,
        format: ImageFormat.PORTRAIT,
      },
    ],
    description: 'Perfect for a night out at the Roxbury.',
    brand: 'Club Room',
    categories: [categories.menShirts],
    price: {
      isoCurrencyCode: 'USD',
      currentPrice: 190,
      discounted: false,
      formattedValue: '$190.00',
      fullPrice: 190,
    },
    stock: {
      productId: at(0),
      quantity: 10,
    },
    reviews: getRandomProductReviews(at(0), 1),
    status: 'AVAILABLE',
    variants: [variants.black, variants.white],
  },
  {
    id: at(1),
    name: 'H&M® Mens Shortsleeve Plaid Dress Shirt',
    images: [
      {
        id: imageAt(2),
        url: 'https://res.cloudinary.com/dgpl87wy6/image/upload/v1688063234/shop/mens-dress-shirt-shortsleeve-plaid_xnlzvu.jpg',
        variantId: variants.thinPlaid.id,
        fileType: ImageFileType.JPG,
        format: ImageFormat.PORTRAIT,
      },
    ],
    description: 'The perfect fit for any man who is over 6 feet tall and only weighs 120 pounds.',
    brand: 'H&M',
    categories: [categories.menShirts],
    price: {
      isoCurrencyCode: 'USD',
      currentPrice: 35,
      discounted: true,
      formattedValue: '$35.00',
      fullPrice: 50,
    },
    stock: {
      productId: at(1),
      quantity: 20,
    },
    reviews: getRandomProductReviews(at(1), 2),
    status: 'AVAILABLE',
    variants: [variants.thinPlaid],
  },
  {
    id: at(2),
    name: 'Tom Ford® Mens Longsleeve Flannel Shirt',
    images: [
      {
        id: imageAt(3),
        url: 'https://res.cloudinary.com/dgpl87wy6/image/upload/v1688063234/shop/mens-dress-shirt-plaid_d2hsng.jpg',
        variantId: variants.fatPlaid.id,
        fileType: ImageFileType.JPG,
        format: ImageFormat.PORTRAIT,
      },
    ],
    description: "Look like the embodiment of everything that killed grunge in the 90's",
    brand: 'Tom Ford',
    categories: [categories.menShirts],
    price: {
      isoCurrencyCode: 'USD',
      currentPrice: 300,
      discounted: false,
      formattedValue: '$300.00',
      fullPrice: 300,
    },
    stock: {
      productId: at(2),
      quantity: 2,
    },
    reviews: getRandomProductReviews(at(2), 1),
    status: 'AVAILABLE',
    variants: [variants.fatPlaid],
  },
  {
    id: at(3),
    name: "Acme® Men's Loose-Fitting Jeans",
    images: [
      {
        id: imageAt(4),
        url: 'https://res.cloudinary.com/dgpl87wy6/image/upload/v1688063237/shop/mens-jeans-loose-fit_dkgqac.jpg',
        variantId: variants.denim.id,
        fileType: ImageFileType.JPG,
        format: ImageFormat.PORTRAIT,
      },
    ],
    description: 'Lorem ipsum solar dit amet.',
    brand: 'Acme',
    categories: [categories.menJeans],
    price: {
      isoCurrencyCode: 'USD',
      currentPrice: 200,
      discounted: false,
      formattedValue: '$200.00',
      fullPrice: 200,
    },
    stock: {
      productId: at(3),
      quantity: 1,
    },
    reviews: getRandomProductReviews(at(3), 3),
    status: 'AVAILABLE',
    variants: [variants.denim],
  },
  {
    id: at(4),
    name: "Acme® Men's Bootcut Jeans",
    images: [
      {
        id: imageAt(5),
        url: 'https://res.cloudinary.com/dgpl87wy6/image/upload/v1688063235/shop/mens-jeans-bootcut_r4ln7e.jpg',
        variantId: variants.denimDark.id,
        fileType: ImageFileType.JPG,
        format: ImageFormat.PORTRAIT,
      },
    ],
    description: 'Lorem ipsum solar dit amet.',
    brand: 'Acme',
    categories: [categories.menJeans],
    price: {
      isoCurrencyCode: 'USD',
      currentPrice: 100,
      discounted: false,
      formattedValue: '$100.00',
      fullPrice: 100,
    },
    stock: {
      productId: at(4),
      quantity: 2,
    },
    reviews: [],
    status: 'AVAILABLE',
    variants: [variants.denimDark],
  },
  {
    id: at(5),
    name: "XXX® Men's Distresed Skinny Jeans",
    images: [
      {
        id: imageAt(6),
        url: 'https://res.cloudinary.com/dgpl87wy6/image/upload/v1688063235/shop/mens-jeans-skinny_vdyqnn.jpg',
        variantId: variants.denimDark.id,
        fileType: ImageFileType.JPG,
        format: ImageFormat.PORTRAIT,
      },
    ],
    description: "We made these jeans look like you live dangerously even though you really don't.",
    brand: 'XXX',
    categories: [categories.menJeans],
    price: {
      isoCurrencyCode: 'USD',
      currentPrice: 500,
      discounted: false,
      formattedValue: '$500.00',
      fullPrice: 500,
    },
    stock: {
      productId: at(5),
      quantity: 3,
    },
    reviews: getRandomProductReviews(at(5), 2),
    status: 'AVAILABLE',
    variants: [variants.denimDark],
  },
  {
    id: at(6),
    name: "Minnetonka® Men's Black Moccasins",
    images: [
      {
        id: imageAt(7),
        url: 'https://res.cloudinary.com/dgpl87wy6/image/upload/v1688063235/shop/mens-shoes-moccasin_ydsoi0.jpg',
        variantId: variants.black.id,
        fileType: ImageFileType.JPG,
        format: ImageFormat.PORTRAIT,
      },
    ],
    description: 'Genuine leather moccasins.',
    brand: 'Minnetonka',
    categories: [categories.menShoes],
    price: {
      isoCurrencyCode: 'USD',
      currentPrice: 180,
      discounted: false,
      formattedValue: '$180.00',
      fullPrice: 180,
    },
    stock: {
      productId: at(6),
      quantity: 0,
    },
    reviews: [],
    status: 'OUT_OF_STOCK',
    variants: [variants.black],
  },
  {
    id: at(7),
    name: "Merrell® Men's Suede Outdoor Shoes",
    images: [
      {
        id: imageAt(8),
        url: 'https://res.cloudinary.com/dgpl87wy6/image/upload/v1688063235/shop/mens-shoes-outdoors_zazg5t.jpg',
        variantId: variants.bone.id,
        fileType: ImageFileType.JPG,
        format: ImageFormat.PORTRAIT,
      },
    ],
    description: 'Suede or su-su-sussudio? Yeah, Phil Collins.',
    brand: 'Merrell',
    categories: [categories.menShoes],
    price: {
      isoCurrencyCode: 'USD',
      currentPrice: 190,
      discounted: false,
      formattedValue: '$190.00',
      fullPrice: 190,
    },
    stock: {
      productId: at(7),
      quantity: 7,
    },
    reviews: getRandomProductReviews(at(7), 1),
    status: 'AVAILABLE',
    variants: [variants.bone],
  },
  {
    id: at(8),
    name: "Alfani® Men's Leather Dress Shoes",
    images: [
      {
        id: imageAt(9),
        url: 'https://res.cloudinary.com/dgpl87wy6/image/upload/v1688063235/shop/mens-shoes-brown_pz2x2n.jpg',
        variantId: variants.brown.id,
        fileType: ImageFileType.JPG,
        format: ImageFormat.PORTRAIT,
      },
    ],
    description: 'Who would wear these?',
    brand: 'Alfani',
    categories: [categories.menShoes],
    price: {
      isoCurrencyCode: 'USD',
      currentPrice: 41,
      discounted: true,
      formattedValue: '$41.00',
      fullPrice: 60,
    },
    stock: {
      productId: at(8),
      quantity: 999,
    },
    reviews: [],
    status: 'AVAILABLE',
    variants: [variants.brown],
  },
  {
    id: at(9),
    name: "DKNY® Women's Flared Floral Dress",
    images: [
      {
        id: imageAt(10),
        url: 'https://res.cloudinary.com/dgpl87wy6/image/upload/v1688063237/shop/womens-dress-floral-01_or3sbs.jpg',
        variantId: variants.floralDark.id,
        fileType: ImageFileType.JPG,
        format: ImageFormat.PORTRAIT,
      },
    ],
    description: 'A flared floral dress.',
    brand: 'DKNY',
    categories: [categories.dresses],
    price: {
      isoCurrencyCode: 'USD',
      currentPrice: 134,
      discounted: false,
      formattedValue: '$134.00',
      fullPrice: 134,
    },
    stock: {
      productId: at(9),
      quantity: 2,
    },
    reviews: getRandomProductReviews(at(9), 1),
    status: 'AVAILABLE',
    variants: [variants.floralDark],
  },
  {
    id: at(10),
    name: 'GUESS® Striped Floral V-Neck Midi Dress',
    images: [
      {
        id: imageAt(11),
        url: 'https://res.cloudinary.com/dgpl87wy6/image/upload/v1688063236/shop/womens-dress-floral-03_filqn2.jpg',
        variantId: variants.floralPink.id,
        fileType: ImageFileType.JPG,
        format: ImageFormat.PORTRAIT,
      },
    ],
    description: 'Striped Floral V-Neck Midi Dress',
    brand: 'GUESS',
    categories: [categories.menShirts],
    price: {
      isoCurrencyCode: 'USD',
      currentPrice: 80,
      discounted: true,
      formattedValue: '$80.00',
      fullPrice: 130,
    },
    stock: {
      productId: at(10),
      quantity: 20,
    },
    reviews: getRandomProductReviews(at(10), 2),
    status: 'AVAILABLE',
    variants: [variants.floralPink],
  },
  {
    id: at(11),
    name: "Calvin Klein® Women's Sleeveless Chiffon A-Line Dress",
    images: [
      {
        id: imageAt(12),
        url: 'https://res.cloudinary.com/dgpl87wy6/image/upload/v1688063235/shop/womens-dress-floral-02_i4idic.jpg',
        variantId: variants.floralTeal.id,
        fileType: ImageFileType.JPG,
        format: ImageFormat.PORTRAIT,
      },
    ],
    description: "Women's Sleeveless Chiffon A-Line Dress",
    brand: 'Calvin Klein',
    categories: [categories.dresses],
    price: {
      isoCurrencyCode: 'USD',
      currentPrice: 85,
      discounted: false,
      formattedValue: '$85.00',
      fullPrice: 85,
    },
    stock: {
      productId: at(11),
      quantity: 8,
    },
    reviews: [],
    status: 'AVAILABLE',
    variants: [variants.floralTeal],
  },
  {
    id: at(12),
    name: "Almost Famous® Women's Stretchy High-Rise Skinny Jeans",
    images: [
      {
        id: imageAt(13),
        url: 'https://res.cloudinary.com/dgpl87wy6/image/upload/v1688063236/shop/womens-jeans-skinny_jogyyh.jpg',
        variantId: variants.denim.id,
        fileType: ImageFileType.JPG,
        format: ImageFormat.PORTRAIT,
      },
    ],
    description: "Women's Stretchy High-Rise Skinny Jeans",
    brand: 'Almost Famous',
    categories: [categories.womenJeans],
    price: {
      isoCurrencyCode: 'USD',
      currentPrice: 20,
      discounted: true,
      formattedValue: '$20.00',
      fullPrice: 38,
    },
    stock: {
      productId: at(12),
      quantity: 1,
    },
    reviews: getRandomProductReviews(at(12), 2),
    status: 'AVAILABLE',
    variants: [variants.denim],
  },
  {
    id: at(13),
    name: "Levi's® Women's Flared Bootcut Jeans",
    images: [
      {
        id: imageAt(14),
        url: 'https://res.cloudinary.com/dgpl87wy6/image/upload/v1688063236/shop/womens-jeans-slim-bootcut_clnizt.jpg',
        variantId: variants.denimDark.id,
        fileType: ImageFileType.JPG,
        format: ImageFormat.PORTRAIT,
      },
    ],
    description: "Women's Flared Bootcut Jeans",
    brand: 'Levi Strauss',
    categories: [categories.womenJeans],
    price: {
      isoCurrencyCode: 'USD',
      currentPrice: 50.0,
      discounted: false,
      formattedValue: '$50.00',
      fullPrice: 50.0,
    },
    stock: {
      productId: at(13),
      quantity: 13,
    },
    reviews: [],
    status: 'AVAILABLE',
    variants: [variants.denimDark],
  },
  {
    id: at(14),
    name: "DKNY® Women's Brown High-Heeled Business Shoes",
    images: [
      {
        id: imageAt(15),
        url: 'https://res.cloudinary.com/dgpl87wy6/image/upload/v1688063236/shop/womens-shoes-high-heel-brown_qmkohg.jpg',
        variantId: variants.brown.id,
        fileType: ImageFileType.JPG,
        format: ImageFormat.PORTRAIT,
      },
    ],
    description: "Women's Brown High-Heeled Business Shoes",
    brand: 'DKNY',
    categories: [categories.womenShoes],
    price: {
      isoCurrencyCode: 'USD',
      currentPrice: 180,
      discounted: false,
      formattedValue: '$180.00',
      fullPrice: 180,
    },
    stock: {
      productId: at(14),
      quantity: 5,
    },
    reviews: [],
    status: 'AVAILABLE',
    variants: [variants.brown],
  },
  {
    id: at(15),
    name: "Gucci® Women's Stylish Black Stilleto Heels",
    images: [
      {
        id: imageAt(16),
        url: 'https://res.cloudinary.com/dgpl87wy6/image/upload/v1688063236/shop/womens-shoes-high-heel-black_qhyv4s.jpg',
        variantId: variants.black.id,
        fileType: ImageFileType.JPG,
        format: ImageFormat.PORTRAIT,
      },
    ],
    description: "Women's Stylish Black Stilleto Heels",
    brand: 'Gucci',
    categories: [categories.womenShoes],
    price: {
      isoCurrencyCode: 'USD',
      currentPrice: 399,
      discounted: false,
      formattedValue: '$399.00',
      fullPrice: 399,
    },
    stock: {
      productId: at(15),
      quantity: 4,
    },
    reviews: [],
    status: 'AVAILABLE',
    variants: [variants.black],
  },
  {
    id: at(16),
    name: "Nike® Women's Running Shoes",
    images: [
      {
        id: imageAt(17),
        url: 'https://res.cloudinary.com/dgpl87wy6/image/upload/v1688063237/shop/womens-shoes-nike-running_szzylp.jpg',
        variantId: variants.white.id,
        fileType: ImageFileType.JPG,
        format: ImageFormat.PORTRAIT,
      },
    ],
    description: "Women's Running Shoes",
    brand: 'Nike',
    categories: [categories.womenShoes],
    price: {
      isoCurrencyCode: 'USD',
      currentPrice: 72,
      discounted: true,
      formattedValue: '$72.00',
      fullPrice: 90,
    },
    stock: {
      productId: at(16),
      quantity: 15,
    },
    reviews: getRandomProductReviews(at(16), 3),
    status: 'AVAILABLE',
    variants: [variants.white],
  },
]
