import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger'

export class CreateProductDto {
  @ApiPropertyOptional()
  brandName?: string

  @ApiProperty({
    description: 'The name of the product',
    example: "Men's Shortsleeve Plaid Dress Shirt",
  })
  name: string

  @ApiProperty({
    description: 'Code of product.',
    example: 'PC1350100',
  })
  code: string

  @ApiProperty({
    description: 'JSON object containing a product description detailing HTML output',
    example: '[{"type": "paragraph","children":[{"text":"100% cotton"}] }]',
  })
  description: string

  @ApiPropertyOptional({
    description: 'The creation date of the product',
    example: '2023-09-03T16:06:24.274Z',
  })
  createdAt?: string | Date

  @ApiProperty({
    description: 'Unique ID that should be generated by the ProductService using uuid.v4',
    example: '7422490d-1400-4727-a8c4-67f27f280d74',
  })
  uid: string

  @ApiPropertyOptional()
  rating?: number
}
